// Mock data for sports betting platform

export const sports = [
  { id: "football", name: "Football", icon: "⚽", count: 245 },
  { id: "basketball", name: "Basketball", icon: "🏀", count: 89 },
  { id: "tennis", name: "Tennis", icon: "🎾", count: 156 },
  { id: "cricket", name: "Cricket", icon: "🏏", count: 42 },
  { id: "baseball", name: "Baseball", icon: "⚾", count: 67 },
  { id: "hockey", name: "Ice Hockey", icon: "🏒", count: 34 },
  { id: "mma", name: "MMA", icon: "🥊", count: 28 },
  { id: "esports", name: "E-Sports", icon: "🎮", count: 112 },
]

export const leagues = [
  { id: "epl", name: "English Premier League", sport: "football", country: "England" },
  { id: "laliga", name: "La Liga", sport: "football", country: "Spain" },
  { id: "bundesliga", name: "Bundesliga", sport: "football", country: "Germany" },
  { id: "seriea", name: "Serie A", sport: "football", country: "Italy" },
  { id: "ligue1", name: "Ligue 1", sport: "football", country: "France" },
  { id: "ucl", name: "UEFA Champions League", sport: "football", country: "Europe" },
  { id: "nba", name: "NBA", sport: "basketball", country: "USA" },
  { id: "euroleague", name: "EuroLeague", sport: "basketball", country: "Europe" },
  { id: "atp", name: "ATP Tour", sport: "tennis", country: "World" },
  { id: "wta", name: "WTA Tour", sport: "tennis", country: "World" },
]

export interface Match {
  id: string
  sport: string
  league: string
  leagueName: string
  homeTeam: string
  awayTeam: string
  homeScore?: number
  awayScore?: number
  startTime: string
  status: "upcoming" | "live" | "finished"
  minute?: number
  odds: {
    home: number
    draw: number
    away: number
  }
  markets: Market[]
}

export interface Market {
  id: string
  name: string
  selections: {
    id: string
    name: string
    odds: number
  }[]
}

export const liveMatches: Match[] = [
  {
    id: "match-1",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Manchester United",
    awayTeam: "Liverpool",
    homeScore: 1,
    awayScore: 2,
    startTime: new Date().toISOString(),
    status: "live",
    minute: 67,
    odds: { home: 3.5, draw: 3.8, away: 1.95 },
    markets: [],
  },
  {
    id: "match-2",
    sport: "football",
    league: "laliga",
    leagueName: "La Liga",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    homeScore: 2,
    awayScore: 2,
    startTime: new Date().toISOString(),
    status: "live",
    minute: 45,
    odds: { home: 2.1, draw: 3.4, away: 3.2 },
    markets: [],
  },
  {
    id: "match-3",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "LA Lakers",
    awayTeam: "Golden State Warriors",
    homeScore: 89,
    awayScore: 94,
    startTime: new Date().toISOString(),
    status: "live",
    minute: 36,
    odds: { home: 1.85, draw: 0, away: 1.95 },
    markets: [],
  },
  {
    id: "match-live-4",
    sport: "tennis",
    league: "atp",
    leagueName: "ATP Tour",
    homeTeam: "Sinner J.",
    awayTeam: "Medvedev D.",
    homeScore: 2,
    awayScore: 1,
    startTime: new Date().toISOString(),
    status: "live",
    minute: 0,
    odds: { home: 1.45, draw: 0, away: 2.65 },
    markets: [],
  },
]

export const upcomingMatches: Match[] = [
  // Football matches
  {
    id: "match-4",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    startTime: new Date(Date.now() + 3600000 * 2).toISOString(),
    status: "upcoming",
    odds: { home: 2.2, draw: 3.3, away: 3.1 },
    markets: [],
  },
  {
    id: "match-5",
    sport: "football",
    league: "bundesliga",
    leagueName: "Bundesliga",
    homeTeam: "Bayern Munich",
    awayTeam: "Borussia Dortmund",
    startTime: new Date(Date.now() + 3600000 * 4).toISOString(),
    status: "upcoming",
    odds: { home: 1.55, draw: 4.2, away: 5.5 },
    markets: [],
  },
  {
    id: "match-8",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Brighton and Hove Albion",
    awayTeam: "West Ham United",
    startTime: new Date(Date.now() + 3600000 * 3).toISOString(),
    status: "upcoming",
    odds: { home: 1.64, draw: 4.33, away: 5.45 },
    markets: [],
  },
  {
    id: "match-9",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Fulham",
    awayTeam: "Crystal Palace",
    startTime: new Date(Date.now() + 3600000 * 5).toISOString(),
    status: "upcoming",
    odds: { home: 2.62, draw: 3.3, away: 2.93 },
    markets: [],
  },
  {
    id: "match-10",
    sport: "football",
    league: "bundesliga",
    leagueName: "Bundesliga",
    homeTeam: "Wolfsburg",
    awayTeam: "RB Leipzig",
    startTime: new Date(Date.now() + 3600000 * 24).toISOString(),
    status: "upcoming",
    odds: { home: 4.74, draw: 4.23, away: 1.73 },
    markets: [],
  },
  {
    id: "match-11",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Chelsea",
    awayTeam: "Everton",
    startTime: new Date(Date.now() + 3600000 * 48).toISOString(),
    status: "upcoming",
    odds: { home: 1.66, draw: 4.17, away: 5.45 },
    markets: [],
  },
  {
    id: "match-12",
    sport: "football",
    league: "seriea",
    leagueName: "Serie A",
    homeTeam: "AC Milan",
    awayTeam: "Inter Milan",
    startTime: new Date(Date.now() + 3600000 * 48).toISOString(),
    status: "upcoming",
    odds: { home: 2.78, draw: 3.14, away: 2.53 },
    markets: [],
  },
  {
    id: "match-13",
    sport: "football",
    league: "ligue1",
    leagueName: "Ligue 1",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    startTime: new Date(Date.now() + 3600000 * 50).toISOString(),
    status: "upcoming",
    odds: { home: 1.45, draw: 4.62, away: 6.03 },
    markets: [],
  },

  {
    id: "match-bball-1",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "Boston Celtics",
    awayTeam: "Miami Heat",
    startTime: new Date(Date.now() + 3600000 * 8).toISOString(),
    status: "upcoming",
    odds: { home: 1.45, draw: 0, away: 2.75 },
    markets: [],
  },
  {
    id: "match-bball-2",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "Denver Nuggets",
    awayTeam: "Phoenix Suns",
    startTime: new Date(Date.now() + 3600000 * 10).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 0, away: 2.25 },
    markets: [],
  },
  {
    id: "match-bball-3",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "Milwaukee Bucks",
    awayTeam: "Philadelphia 76ers",
    startTime: new Date(Date.now() + 3600000 * 24).toISOString(),
    status: "upcoming",
    odds: { home: 1.55, draw: 0, away: 2.45 },
    markets: [],
  },
  {
    id: "match-bball-4",
    sport: "basketball",
    league: "euroleague",
    leagueName: "EuroLeague",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    startTime: new Date(Date.now() + 3600000 * 26).toISOString(),
    status: "upcoming",
    odds: { home: 1.85, draw: 0, away: 1.95 },
    markets: [],
  },

  {
    id: "match-tennis-1",
    sport: "tennis",
    league: "atp",
    leagueName: "ATP Tour",
    homeTeam: "Djokovic N.",
    awayTeam: "Alcaraz C.",
    startTime: new Date(Date.now() + 3600000 * 6).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 0, away: 2.1 },
    markets: [],
  },
  {
    id: "match-tennis-2",
    sport: "tennis",
    league: "atp",
    leagueName: "ATP Tour",
    homeTeam: "Sinner J.",
    awayTeam: "Rune H.",
    startTime: new Date(Date.now() + 3600000 * 12).toISOString(),
    status: "upcoming",
    odds: { home: 1.35, draw: 0, away: 3.25 },
    markets: [],
  },
  {
    id: "match-tennis-3",
    sport: "tennis",
    league: "wta",
    leagueName: "WTA Tour",
    homeTeam: "Swiatek I.",
    awayTeam: "Sabalenka A.",
    startTime: new Date(Date.now() + 3600000 * 14).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 0, away: 2.25 },
    markets: [],
  },
  {
    id: "match-tennis-4",
    sport: "tennis",
    league: "wta",
    leagueName: "WTA Tour",
    homeTeam: "Gauff C.",
    awayTeam: "Rybakina E.",
    startTime: new Date(Date.now() + 3600000 * 18).toISOString(),
    status: "upcoming",
    odds: { home: 2.05, draw: 0, away: 1.78 },
    markets: [],
  },

  {
    id: "match-cricket-1",
    sport: "cricket",
    league: "ipl",
    leagueName: "IPL",
    homeTeam: "Mumbai Indians",
    awayTeam: "Chennai Super Kings",
    startTime: new Date(Date.now() + 3600000 * 20).toISOString(),
    status: "upcoming",
    odds: { home: 1.85, draw: 0, away: 1.95 },
    markets: [],
  },
  {
    id: "match-cricket-2",
    sport: "cricket",
    league: "ipl",
    leagueName: "IPL",
    homeTeam: "Royal Challengers",
    awayTeam: "Kolkata Knight Riders",
    startTime: new Date(Date.now() + 3600000 * 44).toISOString(),
    status: "upcoming",
    odds: { home: 2.15, draw: 0, away: 1.72 },
    markets: [],
  },

  {
    id: "match-mma-1",
    sport: "mma",
    league: "ufc",
    leagueName: "UFC",
    homeTeam: "Islam Makhachev",
    awayTeam: "Charles Oliveira",
    startTime: new Date(Date.now() + 3600000 * 72).toISOString(),
    status: "upcoming",
    odds: { home: 1.55, draw: 0, away: 2.45 },
    markets: [],
  },
  {
    id: "match-mma-2",
    sport: "mma",
    league: "ufc",
    leagueName: "UFC",
    homeTeam: "Jon Jones",
    awayTeam: "Stipe Miocic",
    startTime: new Date(Date.now() + 3600000 * 96).toISOString(),
    status: "upcoming",
    odds: { home: 1.35, draw: 0, away: 3.25 },
    markets: [],
  },

  {
    id: "match-hockey-1",
    sport: "hockey",
    league: "nhl",
    leagueName: "NHL",
    homeTeam: "Toronto Maple Leafs",
    awayTeam: "Montreal Canadiens",
    startTime: new Date(Date.now() + 3600000 * 16).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 4.5, away: 2.15 },
    markets: [],
  },
  {
    id: "match-hockey-2",
    sport: "hockey",
    league: "nhl",
    leagueName: "NHL",
    homeTeam: "New York Rangers",
    awayTeam: "Boston Bruins",
    startTime: new Date(Date.now() + 3600000 * 28).toISOString(),
    status: "upcoming",
    odds: { home: 2.05, draw: 4.2, away: 1.85 },
    markets: [],
  },

  {
    id: "match-esports-1",
    sport: "esports",
    league: "lol",
    leagueName: "LoL Worlds",
    homeTeam: "T1",
    awayTeam: "Gen.G",
    startTime: new Date(Date.now() + 3600000 * 22).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 0, away: 2.25 },
    markets: [],
  },
  {
    id: "match-esports-2",
    sport: "esports",
    league: "csgo",
    leagueName: "CS2 Major",
    homeTeam: "FaZe Clan",
    awayTeam: "Natus Vincere",
    startTime: new Date(Date.now() + 3600000 * 30).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 0, away: 1.85 },
    markets: [],
  },
  {
    id: "match-esports-3",
    sport: "esports",
    league: "dota2",
    leagueName: "Dota 2 TI",
    homeTeam: "Team Spirit",
    awayTeam: "Team Liquid",
    startTime: new Date(Date.now() + 3600000 * 36).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 0, away: 2.1 },
    markets: [],
  },
]

export const footballMatches = [...liveMatches, ...upcomingMatches].filter((m) => m.sport === "football")

export const featuredMatches = [...liveMatches, ...upcomingMatches.slice(0, 3)]

export const userStats = {
  balance: 5250.5,
  totalBets: 156,
  wonBets: 89,
  pendingBets: 12,
  totalWinnings: 8420.75,
}

// Enhanced upcoming matches with more variety
export const additionalMatches: Match[] = [
  // Additional Football Matches
  {
    id: "match-14",
    sport: "football",
    league: "laliga",
    leagueName: "La Liga",
    homeTeam: "Atletico Madrid",
    awayTeam: "Valencia",
    startTime: new Date(Date.now() + 3600000 * 60).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 3.6, away: 3.8 },
    markets: [],
  },
  {
    id: "match-15",
    sport: "football",
    league: "seriea",
    leagueName: "Serie A",
    homeTeam: "Juventus",
    awayTeam: "Napoli",
    startTime: new Date(Date.now() + 3600000 * 62).toISOString(),
    status: "upcoming",
    odds: { home: 2.05, draw: 3.4, away: 3.7 },
    markets: [],
  },
  {
    id: "match-16",
    sport: "football",
    league: "epl",
    leagueName: "English Premier League",
    homeTeam: "Manchester City",
    awayTeam: "Tottenham",
    startTime: new Date(Date.now() + 3600000 * 72).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 4.0, away: 5.0 },
    markets: [],
  },
  {
    id: "match-17",
    sport: "football",
    league: "bundesliga",
    leagueName: "Bundesliga",
    homeTeam: "Bayer Leverkusen",
    awayTeam: "Stuttgart",
    startTime: new Date(Date.now() + 3600000 * 84).toISOString(),
    status: "upcoming",
    odds: { home: 1.85, draw: 3.8, away: 4.2 },
    markets: [],
  },
  {
    id: "match-18",
    sport: "football",
    league: "ligue1",
    leagueName: "Ligue 1",
    homeTeam: "Monaco",
    awayTeam: "Lyon",
    startTime: new Date(Date.now() + 3600000 * 96).toISOString(),
    status: "upcoming",
    odds: { home: 2.25, draw: 3.2, away: 3.1 },
    markets: [],
  },
  // Additional Basketball Matches
  {
    id: "match-bball-5",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "Dallas Mavericks",
    awayTeam: "Houston Rockets",
    startTime: new Date(Date.now() + 3600000 * 36).toISOString(),
    status: "upcoming",
    odds: { home: 1.45, draw: 0, away: 2.75 },
    markets: [],
  },
  {
    id: "match-bball-6",
    sport: "basketball",
    league: "nba",
    leagueName: "NBA",
    homeTeam: "Los Angeles Clippers",
    awayTeam: "Sacramento Kings",
    startTime: new Date(Date.now() + 3600000 * 40).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 0, away: 2.05 },
    markets: [],
  },
  {
    id: "match-bball-7",
    sport: "basketball",
    league: "euroleague",
    leagueName: "EuroLeague",
    homeTeam: "Olympiacos",
    awayTeam: "CSKA Moscow",
    startTime: new Date(Date.now() + 3600000 * 48).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 0, away: 1.85 },
    markets: [],
  },
  // Additional Tennis Matches
  {
    id: "match-tennis-5",
    sport: "tennis",
    league: "atp",
    leagueName: "ATP Tour",
    homeTeam: "Jannik Sinner",
    awayTeam: "Daniil Medvedev",
    startTime: new Date(Date.now() + 3600000 * 32).toISOString(),
    status: "upcoming",
    odds: { home: 1.55, draw: 0, away: 2.45 },
    markets: [],
  },
  {
    id: "match-tennis-6",
    sport: "tennis",
    league: "wta",
    leagueName: "WTA Tour",
    homeTeam: "Aryna Sabalenka",
    awayTeam: "Ons Jabeur",
    startTime: new Date(Date.now() + 3600000 * 40).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 0, away: 2.05 },
    markets: [],
  },
  // Additional Cricket Matches
  {
    id: "match-cricket-3",
    sport: "cricket",
    league: "ipl",
    leagueName: "IPL",
    homeTeam: "Bangalore Royal Challengers",
    awayTeam: "Delhi Capitals",
    startTime: new Date(Date.now() + 3600000 * 64).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 0, away: 1.85 },
    markets: [],
  },
  {
    id: "match-cricket-4",
    sport: "cricket",
    league: "test",
    leagueName: "Test Cricket",
    homeTeam: "India",
    awayTeam: "Australia",
    startTime: new Date(Date.now() + 3600000 * 168).toISOString(),
    status: "upcoming",
    odds: { home: 2.15, draw: 3.5, away: 1.72 },
    markets: [],
  },
  // Additional MMA Matches
  {
    id: "match-mma-3",
    sport: "mma",
    league: "ufc",
    leagueName: "UFC",
    homeTeam: "Alexander Volkanovski",
    awayTeam: "Tom Aspinall",
    startTime: new Date(Date.now() + 3600000 * 120).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 0, away: 2.25 },
    markets: [],
  },
  {
    id: "match-mma-4",
    sport: "mma",
    league: "ufc",
    leagueName: "UFC",
    homeTeam: "Colby Covington",
    awayTeam: "Leon Edwards",
    startTime: new Date(Date.now() + 3600000 * 144).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 0, away: 1.85 },
    markets: [],
  },
  // Additional Hockey Matches
  {
    id: "match-hockey-3",
    sport: "hockey",
    league: "nhl",
    leagueName: "NHL",
    homeTeam: "Colorado Avalanche",
    awayTeam: "St. Louis Blues",
    startTime: new Date(Date.now() + 3600000 * 38).toISOString(),
    status: "upcoming",
    odds: { home: 1.85, draw: 4.3, away: 1.95 },
    markets: [],
  },
  {
    id: "match-hockey-4",
    sport: "hockey",
    league: "nhl",
    leagueName: "NHL",
    homeTeam: "Vegas Golden Knights",
    awayTeam: "Anaheim Ducks",
    startTime: new Date(Date.now() + 3600000 * 52).toISOString(),
    status: "upcoming",
    odds: { home: 1.65, draw: 4.1, away: 2.25 },
    markets: [],
  },
  // Additional E-Sports Matches
  {
    id: "match-esports-4",
    sport: "esports",
    league: "lol",
    leagueName: "LoL Worlds",
    homeTeam: "T1",
    awayTeam: "Damwon Gaming",
    startTime: new Date(Date.now() + 3600000 * 44).toISOString(),
    status: "upcoming",
    odds: { home: 1.55, draw: 0, away: 2.45 },
    markets: [],
  },
  {
    id: "match-esports-5",
    sport: "esports",
    league: "csgo",
    leagueName: "CS2 Major",
    homeTeam: "Heroic",
    awayTeam: "Cloud9",
    startTime: new Date(Date.now() + 3600000 * 54).toISOString(),
    status: "upcoming",
    odds: { home: 1.75, draw: 0, away: 2.05 },
    markets: [],
  },
  {
    id: "match-esports-6",
    sport: "esports",
    league: "dota2",
    leagueName: "Dota 2 TI",
    homeTeam: "Evil Geniuses",
    awayTeam: "Virtus.pro",
    startTime: new Date(Date.now() + 3600000 * 60).toISOString(),
    status: "upcoming",
    odds: { home: 1.95, draw: 0, away: 1.85 },
    markets: [],
  },
]

// Combine all matches for comprehensive demo data
export const allMatches = [...liveMatches, ...upcomingMatches, ...additionalMatches]

// Virtual Games / Casino Games
export interface VirtualGame {
  id: string
  name: string
  category: "slots" | "casino" | "virtual_racing" | "virtual_sports" | "cards"
  minBet: number
  maxBet: number
  rtp: number // Return to Player percentage
  volatility: "low" | "medium" | "high"
  featured?: boolean
  players?: number
  image?: string | null
}

export const virtualGames: VirtualGame[] = [
  // Virtual Racing Games
  {
    id: "virtual-racing-1",
    name: "Virtual Horse Racing",
    category: "virtual_racing",
    minBet: 1,
    maxBet: 1000,
    rtp: 96.5,
    volatility: "medium",
    featured: true,
    players: 2345,
    image: "/games/horse-racing.png",
  },
  {
    id: "virtual-racing-2",
    name: "Greyhound Racing",
    category: "virtual_racing",
    minBet: 0.5,
    maxBet: 500,
    rtp: 97.2,
    volatility: "low",
    players: 1876,
    image: "/games/greyhound-racing.png",
  },
  {
    id: "virtual-racing-3",
    name: "Virtual Car Racing",
    category: "virtual_racing",
    minBet: 2,
    maxBet: 2000,
    rtp: 95.8,
    volatility: "high",
    featured: true,
    players: 3421,
    image: "/games/car-racing.png",
  },
  // Virtual Sports Games
  {
    id: "virtual-sports-1",
    name: "Virtual Football",
    category: "virtual_sports",
    minBet: 1,
    maxBet: 500,
    rtp: 97.0,
    volatility: "medium",
    featured: true,
    players: 5234,
    image: "/games/football.png",
  },
  {
    id: "virtual-sports-2",
    name: "Virtual Tennis",
    category: "virtual_sports",
    minBet: 0.5,
    maxBet: 300,
    rtp: 96.8,
    volatility: "low",
    players: 1543,
    image: "/games/tennis.png",
  },
  {
    id: "virtual-sports-3",
    name: "Virtual Basketball",
    category: "virtual_sports",
    minBet: 1.5,
    maxBet: 600,
    rtp: 96.2,
    volatility: "medium",
    players: 2876,
    image: "/games/basketball.png",
  },
  // Slot Games
  {
    id: "slot-1",
    name: "Dragon's Gold",
    category: "slots",
    minBet: 0.1,
    maxBet: 100,
    rtp: 96.0,
    volatility: "high",
    featured: true,
    players: 4567,
    image: null,
  },
  {
    id: "slot-2",
    name: "Treasure Quest",
    category: "slots",
    minBet: 0.05,
    maxBet: 50,
    rtp: 97.5,
    volatility: "low",
    players: 3421,
    image: null,
  },
  {
    id: "slot-3",
    name: "Lucky 7s",
    category: "slots",
    minBet: 0.1,
    maxBet: 250,
    rtp: 95.5,
    volatility: "medium",
    featured: true,
    players: 2109,
    image: null,
  },
  {
    id: "slot-4",
    name: "Mystic Forest",
    category: "slots",
    minBet: 0.2,
    maxBet: 150,
    rtp: 96.8,
    volatility: "medium",
    players: 1765,
    image: null,
  },
  {
    id: "slot-5",
    name: "Golden Temple",
    category: "slots",
    minBet: 0.1,
    maxBet: 200,
    rtp: 97.0,
    volatility: "low",
    featured: true,
    players: 3892,
    image: null,
  },
  // Casino Games
  {
    id: "casino-1",
    name: "Live Roulette",
    category: "casino",
    minBet: 1,
    maxBet: 5000,
    rtp: 97.3,
    volatility: "low",
    featured: true,
    players: 6234,
    image: null,
  },
  {
    id: "casino-2",
    name: "Live Blackjack",
    category: "casino",
    minBet: 1,
    maxBet: 2000,
    rtp: 99.6,
    volatility: "low",
    featured: true,
    players: 5678,
    image: null,
  },
  {
    id: "casino-3",
    name: "Live Baccarat",
    category: "casino",
    minBet: 1,
    maxBet: 3000,
    rtp: 98.6,
    volatility: "low",
    players: 3456,
    image: null,
  },
  {
    id: "casino-4",
    name: "Live Poker",
    category: "casino",
    minBet: 2,
    maxBet: 10000,
    rtp: 98.0,
    volatility: "medium",
    featured: true,
    players: 4321,
    image: null,
  },
  // Card Games
  {
    id: "card-1",
    name: "Hi-Lo Card Game",
    category: "cards",
    minBet: 0.5,
    maxBet: 500,
    rtp: 97.8,
    volatility: "medium",
    players: 1234,
    image: null,
  },
  {
    id: "card-2",
    name: "Keno",
    category: "cards",
    minBet: 1,
    maxBet: 1000,
    rtp: 96.0,
    volatility: "high",
    players: 2567,
    image: null,
  },
]
